### ISSUE TITLE
Error: Cannot find module 'eslint/lib/formatters/stylish'

### ISSUE THREAD

**Issue by artur79** [HashemKhalifa/webpack-react-boilerplate#172]
I'v just cloned the repo, runned `npm install` than `npm start` and I'v got:

```
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {main} [built]
[./src/index.jsx] 457 bytes {main} [built] [failed] [1 error]
    + 20 hidden modules

ERROR in ./src/index.jsx
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint/lib/formatters/stylish'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.module.exports (/Users/artur/Work/webpack-react-boilerplate/node_modules/eslint-loader/index.js:199:26)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
```

Also during install I'v got the warnings:

```
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.2 requires a peer of eslint@>=1.6.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-watch@5.1.2 requires a peer of eslint@>=4 <6.0.0 but none is installed. You must install peer dependencies yourself.
```

`npm test` runs with no issues

**Comment by artur79** [comment]
I'v managed to overcome this issue by updating _webpack.common.js_ file with:

```
        options: {
          formatter: require('eslint').CLIEngine.getFormatter('stylish'),
          emitWarning: process.env.NODE_ENV !== 'production',
        },
```

**Comment by artur79** [comment]
I'v opened the PR which resolves encountered issues descibed above:

https://github.com/HashemKhalifa/webpack-react-boilerplate/pull/173
